name: Generate ASCII Artwork
on: pull_request

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
          - name: Install cowsay
            run: sudo apt install cowsay -y

          - name: Execute cowsay command
            run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

          - name: Upload dragon text file
            uses: actions/upload-artifact@v4
            with:
                name: dragon-text-file
                path: ./dragon.txt

    test_job_1:
        runs-on: ubuntu-latest
        needs: build_job_1
        steps:
          - name: Download dragon text file
            uses: actions/download-artifact@v4
            with:
                name: dragon-text-file

          - name: Test if file exists
            run: grep -i "dragon" dragon.txt

    deploy_job_1:
        runs-on: ubuntu-latest
        needs: test_job_1
        steps:
          - name: Download dragon text file
            uses: actions/download-artifact@v4
            with:
                name: dragon-text-file

          - name: Read File
            run: cat dragon.txt
