name: Generate ASCII Artwork

on: push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
          - name: Install cowsay
            run: sudo apt install cowsay -y

          - name: Execute cowsay command
            run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

          - name: Sleep for 15 seconds
            run: sleep 15

    test_job_1:
        runs-on: ubuntu-latest
        needs: build_job_1
        steps:
          - name: Sleep for 5 seconds
            run: sleep 5

          - name: Test if file exists
            run: grep -i "dragon" dragon.txt

    deploy_job_1:
        runs-on: ubuntu-latest
        needs: test_job_1
        steps:
          - name: Read File
            run: cat dragon.txt
